"""A small CLI-based SQL agent.

This script demonstrates how to use LangChain's SQLDatabase toolkit along
with an LLM to generate SQL queries and execute them against a database.
"""

import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from utils import load_chat_model
from langchain_openai import ChatOpenAI
from sqlalchemy import create_engine
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.utilities import SQLDatabase


DB_URL = os.environ.get("DB_URL", "sqlite:///:memory:")
# When set, only these tables will be visible to the agent.
INCLUDE_TABLES: Optional[List[str]] = None  # e.g. ["my_table", "another_table"]

# Path to the precomputed data dictionary (generated by dd.py).
DATA_DICTIONARY_PATH = os.environ.get("DATA_DICTIONARY_PATH", "data_dictionary.json")

# For safety: always cap query results returned to the user.
TOP_K_DEFAULT = 20

llm: ChatOpenAI = load_chat_model()
engine = create_engine(DB_URL)
db = SQLDatabase(engine, include_tables=INCLUDE_TABLES)
# Some SQLDatabase implementations expose a `dialect` property.
# Fall back to a generic SQL dialect string if not available.
dialect = getattr(db, "dialect", "sql")

toolkit = SQLDatabaseToolkit(db=db, llm=llm)
tools = toolkit.get_tools()

list_tables_tool = next(t for t in tools if t.name == "sql_db_list_tables")
get_schema_tool = next(t for t in tools if t.name == "sql_db_schema")
run_query_tool = next(t for t in tools if t.name == "sql_db_query")


def load_data_dictionary(path: str) -> Dict[str, Any]:
    """Load (and cache) the data dictionary JSON produced by dd.py."""

    path_obj = Path(path)
    if not path_obj.exists():
        return {}

    try:
        with path_obj.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _tokenize(text: str) -> List[str]:
    return [t for t in re.findall(r"[A-Za-z0-9_]+", text.lower()) if len(t) > 1]


def _build_schema_index(data_dict: Dict[str, Any]) -> Tuple[Dict[str, Set[str]], Dict[str, Set[str]]]:
    """Build a simple keyword-to-table/column index for fast relevance scoring."""

    table_index: Dict[str, Set[str]] = {}
    column_index: Dict[str, Set[str]] = {}

    for table_name, info in data_dict.items():
        lower_table = table_name.lower()
        for token in re.findall(r"[A-Za-z0-9_]+", lower_table):
            table_index.setdefault(token, set()).add(table_name)

        for col in info.get("columns", []):
            col_name = col.get("name", "").lower()
            for token in re.findall(r"[A-Za-z0-9_]+", col_name):
                column_index.setdefault(token, set()).add(table_name)

    return table_index, column_index


def _select_candidate_tables(
    question: str,
    data_dict: Dict[str, Any],
    max_tables: int = 3,
) -> List[str]:
    """Pick a small set of relevant tables based on the question.

    Keeping this list small drastically reduces prompt size and helps the LLM
    create efficient, focused queries.
    """

    if not data_dict:
        return []

    question_tokens = set(_tokenize(question))
    table_index, column_index = _build_schema_index(data_dict)

    scores: Dict[str, int] = {}
    for tok in question_tokens:
        for tbl in table_index.get(tok, []):
            scores[tbl] = scores.get(tbl, 0) + 3
        for tbl in column_index.get(tok, []):
            scores[tbl] = scores.get(tbl, 0) + 1

    # Pick the top scoring tables.
    ranked = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))
    if not ranked:
        return []
    return [t for t, _ in ranked[:max_tables]]


def _format_schema_for_prompt(data_dict: Dict[str, Any], tables: List[str]) -> str:
    """Turn selected schema metadata into a compact prompt-friendly block."""

    if not tables:
        return ""

    blocks: List[str] = [
        "Known schema (table -> columns / description):",
    ]
    for table in tables:
        info = data_dict.get(table, {})
        cols = info.get("columns", [])
        col_lines: List[str] = []
        for col in cols:
            name = col.get("name")
            desc = col.get("col_description") or col.get("type") or ""
            col_lines.append(f"  - {name}: {desc}".strip())
        blocks.append(f"{table}:\n" + "\n".join(col_lines[:20]))
        if len(col_lines) > 20:
            blocks.append(f"  ... ({len(col_lines) - 20} more columns)")
    return "\n".join(blocks)


def _apply_result_limit(query: str, top_k: int) -> str:
    """Ensures the query returns at most top_k rows to avoid long-running scans."""

    # Simple heuristic: if the query already contains a LIMIT/FETCH/ROWNUM clause, keep it.
    lc = query.lower()
    if "limit" in lc or "fetch first" in lc or "rownum" in lc:
        return query

    # Try to append a LIMIT clause if it makes sense.
    return query.strip().rstrip(";") + f" LIMIT {top_k}"


def _make_tool_call(name: str, args: Dict[str, Any]) -> Dict[str, Any]:
    return {"name": name, "args": args, "id": f"{name}_call", "type": "tool_call"}


def list_tables() -> List[str]:
    """Return a list of table names exposed to the SQL toolkit."""

    tool_call = _make_tool_call("sql_db_list_tables", {})
    raw = list_tables_tool.invoke(tool_call)
    if isinstance(raw, list):
        return raw
    if isinstance(raw, str):
        return [line.strip() for line in raw.splitlines() if line.strip()]
    return []


def get_schema(table_names: Optional[List[str]] = None) -> Any:
    """Return the schema for the provided table(s)."""

    args: Dict[str, Any] = {}
    if table_names is not None:
        args["table_names"] = table_names
    tool_call = _make_tool_call("sql_db_schema", args)
    return get_schema_tool.invoke(tool_call)


def run_sql_query(query: str) -> Any:
    """Execute a SQL query via the toolkit tool."""

    tool_call = _make_tool_call("sql_db_query", {"query": query})
    return run_query_tool.invoke(tool_call)


GENERATE_QUERY_SYSTEM_PROMPT = """
You are an agent designed to interact with a SQL database.
Given an input question, create a syntactically correct {dialect} query to run,
then look at the results of the query and return the answer.
Unless the user specifies a specific number of examples they wish to obtain,
always limit your query to at most {top_k} results.

You can order the results by a relevant column to return the most interesting
examples in the database. Never query for all the columns from a specific table,
only ask for the relevant columns given the question.

DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.
""".strip()


CHECK_QUERY_SYSTEM_PROMPT = """
You are a SQL expert with a strong attention to detail.
Double check the {dialect} query for common mistakes, including:
- Using NOT IN with NULL values
- Using UNION when UNION ALL should have been used
- Using BETWEEN for exclusive ranges
- Data type mismatch in predicates
- Properly quoting identifiers
- Using the correct number of arguments for functions
- Casting to the correct data type
- Using the proper columns for joins

If there are any of the above mistakes, rewrite the query. If there are no mistakes,
just reproduce the original query.
""".strip()


def generate_query(question: str, top_k: int = TOP_K_DEFAULT) -> str:
    """Generate a SQL query for the user question using schema hints.

    We use the precomputed data dictionary to guide the model toward a small
    set of relevant tables/columns, which reduces the chance of long-running
    queries and avoids scanning the full 1500-table schema.
    """

    data_dict = load_data_dictionary(DATA_DICTIONARY_PATH)
    candidate_tables = _select_candidate_tables(question, data_dict, max_tables=2)
    schema_hint = _format_schema_for_prompt(data_dict, candidate_tables)

    system_prompt = GENERATE_QUERY_SYSTEM_PROMPT.format(dialect=dialect, top_k=top_k)
    system_message = {
        "role": "system",
        "content": (
            system_prompt
            + "\n\n" + schema_hint
            + "\n\nOnly use the above tables and columns when generating the query."
        ),
    }
    user_message = {"role": "user", "content": question}

    response = llm.invoke([system_message, user_message])
    query = getattr(response, "content", str(response)).strip()

    return _apply_result_limit(query, top_k)


def check_query(query: str) -> str:
    """Review the query for common issues and (optionally) rewrite it."""

    system_prompt = CHECK_QUERY_SYSTEM_PROMPT.format(dialect=dialect)
    system_message = {"role": "system", "content": system_prompt}
    user_message = {"role": "user", "content": query}

    response = llm.invoke([system_message, user_message])
    checked = getattr(response, "content", str(response)).strip()
    return _apply_result_limit(checked, TOP_K_DEFAULT)


def main() -> None:
    print(f"Connected to database: {DB_URL}")

    data_dict = load_data_dictionary(DATA_DICTIONARY_PATH)
    if data_dict:
        tables = sorted(data_dict.keys())
        print(f"Loaded schema for {len(tables)} tables from {DATA_DICTIONARY_PATH}")
        print("Example tables:", ", ".join(tables[:10]))
    else:
        # Fall back to a database call if no precomputed schema is available.
        print("No data dictionary found; listing tables from the database...")
        print("Available tables:", list_tables())

    question = input("\nEnter a natural language question to run against the database: ").strip()
    if not question:
        print("No question provided. Exiting.")
        return

    query = generate_query(question)
    print("\nGenerated query:\n", query)

    checked_query = check_query(query)
    if checked_query != query:
        print("\nRewrite after checks:\n", checked_query)

    print("\nExecuting query...")
    result = run_sql_query(checked_query)
    print("\nQuery result:\n", result)


if __name__ == "__main__":
    main()

